### ISSUE TITLE
Recursive _get_license_info does not yield recursive results

### ISSUE THREAD

**Issue by dave4422** [blackducksoftware/hub-rest-api-python#108]
Hello,
method  _get_license_info(self, license_obj),  line 631 should be change from 
``
self._get_license_info(license)
``
to
``
yield from self._get_license_info(license)
``

to also yield the recursive (nested) results.
Best wishes,
David

**Comment by gsnyder2007** [comment]
David,

Thanks for that feedback. I'll investigate tomorrow and (hopefully) push a fix, unless you already have a pull request you want to make. Let me know.

**Comment by gsnyder2007** [comment]
Ugh, sorry for the delay in closing the loop on this one. I see that the method now uses the yield as proposed so I must have already fixed it. I just (re-) tested it and everything appears to be working ok so I'm going to close this.
