### ISSUE TITLE
beware of limits

### ISSUE THREAD

**Issue by pjsnps** [blackducksoftware/hub-rest-api-python#115]
If you have a large Black Duck (Hub) instance, and you do not see an expected record in your output, you probably have exceeded a default limit hiding in 
`hub-rest-api-python/blackduck/HubRestApi.py`

For example:
`    def get_projects(self, limit=100, parameters={}):`

To change the default, add a parameter "limit=1000", like so:  
```
hub = HubInstance(urlbase, username, password, insecure=True)
#projects = hub.get_projects()
projects = hub.get_projects(limit=1000)
print(json.dumps(projects.get('items', [])))
```

**Comment by gsnyder2007** [comment]
Thanks for submitting this Pete. Yes, you can override the default limit the way you have shown.

The Black Duck REST API actually uses two parameters, **offset** and **limit**, to control what is retrieved. In cases where the items being retrieved are particularly large it is a good practice to use both parameters to iterate through all the available items (aka results). Maybe the action here is to make it more apparent how a caller of get_projects could use both (offset and limit) to iterate over the 1000+ projects by grabbing 100 at-a-time?
