### ISSUE TITLE
Problem .restconfig.json with unwritable working directory

### ISSUE THREAD

**Issue by axhe** [blackducksoftware/hub-rest-api-python#119]
There seems to be an issue if the API Client is used in an environment where the working directory is not writable for the process using the .restconfig.json. 

I would prefer that HubInstance can be used in a way without ever trying to access that file altogether if it is instantiated with proper url and credentials. Configuration should be doable external, HubInstance should not try to leak/persist the secrets anywhere else than in memory.

I stumbled upon this when i tried to use the client in an Azure Function. Sure one could simply deploy a working .restconfig.json along with the function, but that would be insecure.

**Comment by skiyooka** [comment]
I ran into the same issue when understanding what HubInstance does behind the scenes. I de-tangled things in the following manner (using argparse) in order to bypass .restconfig.json when explicitly passing credentials but it will ultimately result in significantly more code in the originating script in order to maintain backwards compatibility.

`

    import argparse
    import logging

    loggingLevel = logging.DEBUG
    logging.basicConfig(stream=sys.stdout, format='%(threadName)s: %(asctime)s: %(levelname)s: %(message)s', level=loggingLevel)

    from blackduck.HubRestApi import HubInstance

    parser = argparse.ArgumentParser(description="...")

    # must specify authentication details (i.e. token file or username/password) on command line or in .restconfig.json
    parser.add_argument('--urlbase', dest='urlbase', default=None, help="Hub server URLBASE e.g. https://example.com");
    parser.add_argument('--token-file', dest='token_file', default=None, help="File containing access token");
    parser.add_argument('--username', dest='username', default=None, help="Hub server USERNAME");
    parser.add_argument('--password', dest='password', default=None, help="Hub server PASSWORD");

    args = parser.parse_args()

    create_config = False
    if (create_config): logging.info("writing .restconfig.json upon successful authentication")

    accept_self_signed = True
    if (accept_self_signed): logging.info("accepting self-signed certificates in SSL connection")

    hub = None
    if (args.urlbase and args.username and args.password):
        hub = HubInstance(args.urlbase, args.username, args.password, write_config_flag=create_config, insecure=accept_self_signed)
    elif (args.urlbase and args.token_file):
        f = open(args.token_file)
        token = f.readline().strip()
        hub = HubInstance(args.urlbase, api_token=token, write_config_flag=create_config, insecure=accept_self_signed)
    else:
        if not os.path.exists(".restconfig.json"):
            print("Error: authentication details not specified")
            parser.print_help()
            sys.exit(-1)
        logging.info("reading authentication details from .restconfig.json")
        hub = HubInstance()`

**Comment by axhe** [comment]
Thank you, 
that worked for me with the write_config_flag=
