### ISSUE TITLE
Module 'requests.packages' has no 'urllib3' member

### ISSUE THREAD

**Issue by manohargss** [blackducksoftware/hub-rest-api-python#132]
I am getting this issue in HubRestApi.py. I installed all the requirements but I am still getting this error.

**Comment by gsnyder2007** [comment]
First, what is it you're trying to do? Do you just want to use the blackduck library in PyPi to use the Black Duck REST API? Or do you want to do some work on the library itself?

The above error appears to be something wrong in your python environment. Can you confirm or share the following?

python --version 
pip --version 

The code in this repository only supports python3.

I highly recommend use of virtualenv (or some equivalent) to totally isolate the python env, and ensure a clean setup of same.
