### ISSUE TITLE
valid_categories don't contain UPGRADE_GUIDANCE as one of the category in Reporting.py file.

### ISSUE THREAD

**Issue by rishianand06** [blackducksoftware/hub-rest-api-python#150]
To create a version report, there are different categories for a given report and as per the BlackDuck documentation, the possible values are [VERSION, CODE_LOCATIONS, COMPONENTS, SECURITY, FILES, CRYPTO_ALGORITHMS, PROJECT_VERSION_CUSTOM_FIELDS, BOM_COMPONENT_CUSTOM_FIELDS, LICENSE_TERM_FULFILLMENT, UPGRADE_GUIDANCE].

But if you see **Reporting.py** module, then valid_categories are defined as -
https://github.com/blackducksoftware/hub-rest-api-python/blob/master/blackduck/Reporting.py#L11
It doesn't contain **UPGRADE_GUIDANCE** as one of the category.

**Comment by AR-Calder** [comment]
closing as reported fixed in #151
