### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil' in v1.0.1

### ISSUE THREAD

**Issue by trv-tsingkof** [blackducksoftware/hub-rest-api-python#166]
After upgrading to version 1.0.1 from 0.0.56, my existing scripts utilizing the `blackduck` module break with the following exception:

```
Traceback (most recent call last):
  File "myScript.py", line 6, in <module>
    from blackduck.HubRestApi import HubInstance
  File "/opt/python-3.9.2/lib/python3.9/site-packages/blackduck/__init__.py", line 2, in <module>
    from .HubRestApi import HubInstance
  File "/opt/python-3.9.2/lib/python3.9/site-packages/blackduck/HubRestApi.py", line 55, in <module>
    from .Utils import object_id
  File "/opt/python-3.9.2/lib/python3.9/site-packages/blackduck/Utils.py", line 9, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
```

Looking through the code, I do see python-dateutils defined in the requirements.txt file, but it doesn't seem like the full set of required packages are defined in the [setup.py](https://github.com/blackducksoftware/hub-rest-api-python/blob/0ed995384addf09fcda2fef7436f1b699ec84236/setup.py#L25) file, so pip doesn't know to install it.

The obvious workaround is for me to `pip install python-dateutils` manually when I need to use the blackduck module, but ideally running `pip install blackduck` would automatically install everything it needs.

**Comment by AR-Calder** [comment]
Fixed `setup.py` @gsnyder2007 or @skiyooka - could one of you update pypi?

**Comment by skiyooka** [comment]
PyPI is updated with 1.0.2 and I tested pip install blackduck with just pip and setuptools installed and it pulls everything in correctly. Thank you @trv-tsingkof for the report and @AR-Calder for the fix.
