### ISSUE TITLE
No license is assigned to project on creation

### ISSUE THREAD

**Issue by lcsongor** [blackducksoftware/hub-rest-api-python#179]
The REST API of Blackduck supports assigning a license to a new project, upon creation, however there is no support for this in this Python library. 
The issue is in 
Versions.py: 
def add_version_as_component(self, main_project_release, sub_project_release):
line 20 in the latest version 
This is necessary to properly create new projects, which have an initial license.

**Comment by AR-Calder** [comment]
Hey @lcsongor, if you have a fix for the issue already, perhaps you could create a PR with it?
