### ISSUE TITLE
IN data bricks - SLError: HTTPSConnectionPool(host='jda.blackducksoftware.com', port=443): Max retries exceeded with url: /j_spring_security_check (Caused by SSLError(SSLError("bad handshake: SysCallError(110, 'ETIMEDOUT')")))

### ISSUE THREAD

**Issue by hanman2016** [blackducksoftware/hub-rest-api-python#183]
![image](https://user-images.githubusercontent.com/25268672/122587743-d51e0000-d07b-11eb-9382-ca4c6c44735a.png)

Hi ,

I am getting below error when running in azure datbricks envrironment , i provided all correct url,user and password 

hub = HubInstance(urlbase, username, password, insecure=True)
SLError: HTTPSConnectionPool(host='jda.blackducksoftware.com', port=443): Max retries exceeded with url: /j_spring_security_check (Caused by SSLError(SSLError("bad handshake: SysCallError(110, 'ETIMEDOUT')")))

**Comment by skiyooka** [comment]
Hello, this looks like a lower level SSL error which I cannot reproduce on my end. I recommend trying the following script (which gets hub-rest-api-python out of the picture). If the script does not work please open a technical support ticket with Synopsys.

    import requests
    from pprint import pprint

    credentials = {
        'j_username': "sysadmin",
        'j_password': "PASSWORD"  # TODO: update as necessary
    }

    session = requests.session()

    response = session.post(
        url="https://jda.blackducksoftware.com/j_spring_security_check",
        data=credentials,
        # verify=False,  # SSL certificate validation
    )

    if response.status_code == 204:
        print("Successfully authenticated")
    else:
        print(f"Authentication failed with status code {response.status_code}")
        pprint(response)
        pprint(response.content)

**Comment by AR-Calder** [comment]
Closing as this appears to be a user/environment specific issue . Feel free to reopen if you can provide a repro.
