### ISSUE TITLE
license risk

### ISSUE THREAD

**Issue by 0c0c0f** [blackducksoftware/hub-rest-api-python#186]
![image](https://user-images.githubusercontent.com/34776076/125458543-fe8bdb83-3f3e-48dc-a2f9-d6aadc57695d.png)
![image](https://user-images.githubusercontent.com/34776076/125458584-b9a82197-58eb-4011-ae3b-0673dc5b8941.png)

**Comment by AR-Calder** [comment]
What is your question/issue? The above gives no indication.
