### ISSUE TITLE
Assign a new role to a user in a project

### ISSUE THREAD

**Issue by 3cpt** [blackducksoftware/hub-rest-api-python#191]
[Projects.py#L380](https://github.com/blackducksoftware/hub-rest-api-python/blob/c9bd042462881126de7e53dcf63c289c7443f6d8/blackduck/Projects.py#L380)

Saw this comment. Any idea or suggestion? As a workaround, I tried to do the POST manually, but I get a 412.

Thanks

**Comment by Coulicoula** [comment]
Try to set the Headers content-type with:
headers['Content-Type'] = 'application/vnd.blackducksoftware.internal-1+json'
=>  It should avoid the 412.
By crafting the post request myself, I can add role to a user already in a project

**Comment by 3cpt** [comment]
Didn't try that option, but I tried the _Assigning a Role to a User_ endpoint (`/api/users/{userId}/roles`) that is available in the REST API documentation, and it works too.
