### ISSUE TITLE
KeyError: 'versionName'

### ISSUE THREAD

**Issue by cint2021** [blackducksoftware/hub-rest-api-python#192]
HI,

Without any changes we are receiving the message KeyError: 'versionName' when running scans using
comand like docker
run --rm registry.imagesXXXX.com/il-blackduck-api:latest validate_project_by_scan_name.py -n project-name

result:
scanVersion = obj['versionName']
KeyError: 'versionName'

[validate_project_by_scan_name.txt](https://github.com/blackducksoftware/hub-rest-api-python/files/7006112/validate_project_by_scan_name.txt)

version used :
VERSION = (0, 0, 56)
version = '.'.join(map(str, VERSION))

Any changes around the APIs regards?

**Comment by cint2021** [comment]
maybe some structures was changed:

logging.debug(code_location['name'])
    sections = urlparse(code_location['mappedProjectVersion'])
    data = sections.path.split("/")
    project = data[3]
    version = data[5]
 obj = hub.get_version_by_id("/"+project,version)
    print(obj)

**returns:**

    {​​​​​​'timestamp': '2021-08-18T12:03:31.111Z', 'status': 500, 'error': 'Internal Server Error', 'message': 'The request was rejected because the URL was not normalized.', 'path': '/api/projects//7c9f1837-9f92-43dd-8f4a-02c5dbdf9245/versions/c589b07e-ab87-4f28-8d41-d9dc9d494246'}​​​​​​

**Comment by AR-Calder** [comment]
The above is complaining because of the slash you are adding to the url on this line
`obj = hub.get_version_by_id("/"+project,version)`
The url constuction for that method looks like this:
` self._get_projects_url() + "/" + project_id + "/versions/" + version_id`
So you should only need:
`obj = hub.get_version_by_id(project,version)`

**Comment by cint2021** [comment]
thanks Andrew, this fixed it;  appreciated your time

**Comment by cint2021** [comment]
case closed
