### ISSUE TITLE
Supported Api's List

### ISSUE THREAD

**Issue by Jojomas123** [blackducksoftware/hub-rest-api-python#2]
Hi,

I'm looking for a list of supported Api's.
Are the ones covered in this project all of them?

I'm interested in the vulnerabilities found in components or generating reports on the API level but an API url like this:

http://server/api/projects/id/versions/id/vulnerable-bom-components

Only redirects to the UI instead.

Any idea?

**Comment by AR-Calder** [comment]
You can find API documentation at `https://<url>/api-doc/public.html` and client documentation on our wiki.
