### ISSUE TITLE
Question : find a resource based on its internal id

### ISSUE THREAD

**Issue by TristanFAURE** [blackducksoftware/hub-rest-api-python#227]
Hello all
first thank you for this python library very convenient and useful.
I have a question about getting a ressource from its internal id.

I found a workaround using get_json method: 
```python
bd = Client(base_url=args.url, token=args.token)
json = bd.get_json(f'api/components/{component_id}')
```

But I would prefer to not be dependent to the URL structure I would prefer something like that but I did not succeed to write the correct query:

```python
bd = Client(base_url=args.url, token=args.token)
params = {
        'q': [f"<someting_UUID_guid???>:{component}"],
        'limit': 1
}
components = [c for c in bd.get_resource('components', params=params) if c['<someting_UUID_guid???>'] == component]
```

Is it possible to have the unique id as a parameter of the query ? If not is it possible to add it ?
Regards

**Comment by OffBy0x01** [comment]
Although there are some blackduck folks among us maintainers, for product enhancements & feedback you'd be better off reaching out to Sig support or your technical account manager. 

That said, the API is not designed to work that way, it would require fundamental changes which we are unlikely to see. 

There are very few scenarios where you'd need to cut and paste uuids, have you considered just using the full url for each resource? It is available via the built-in`href` field.

**Comment by TristanFAURE** [comment]
Thanks for your answer
Yes I will reach my support team.

Actually why I wanted to used uuid is because I want to implement an export / import process :
as a user I export blackduck data in csv format
as a user i edit the csv to update values (particularly custom fields)
as a user i run a script to import updated data.

Because uuids are generated in the blackduck csv report it was convenient for me to reuse them to find my objects to update
