### ISSUE TITLE
get_vulnerable_bom_components is failing due to core.rest.excessive_request, when running the example, generate_vulnerability_remediation_info.py

### ISSUE THREAD

**Issue by mithunpandey** [blackducksoftware/hub-rest-api-python#230]
example run : hub-rest-api-python\examples\generate_vulnerability_remediation_info.py
BD version used is BLACK DUCKv2022.10.2, given below is the output from local debugging

watch Expression  : hub.get_vulnerable_bom_components(version)

result = {dict: 6} {'logRef': 'hub-webapp_PYKGidD7', 'errorMessage': 'Due to performance constraints, asking for large amounts of paginated data is not allowed', 'arguments': {}, 'errorCode': '{core.rest.excessive_request}', 'errors': [], 'links': []}
 'logRef' = {str} 'hub-webapp_PYKGidD7'
 'errorMessage' = {str} 'Due to performance constraints, asking for large amounts of paginated data is not allowed'
 'arguments' = {dict: 0} {}
 'errorCode' = {str} '{core.rest.excessive_request}'
 'errors' = {list: 0} []
 'links' = {list: 0} []
 __len__ = {int} 6

**Comment by OffBy0x01** [comment]
As per the readme:
> The old HubInstance interface and many of the examples using it do not perform paging and will break as a result of the changes in v2022.2.

You may want to take a look at examples from `hub-rest-api-python/examples/client` which uses the new interface.
