### ISSUE TITLE
503 on function download_notification_report for report format JSON

### ISSUE THREAD

**Issue by bmos1** [blackducksoftware/hub-rest-api-python#239]
When generating an JSON report in the Black Duck UI the HUB will display the error "Unable to read report contents due to an unarchive operation error" when the generated report is too large to be read in the application. Error: 503

The provided fix patches with the broken function download_notification_report by replacing the download link from "content" to  "download". The patched function always downloads the report as ZIP file like it was before for TEXT format only. Now the return value is consistent for all type of reports.

We provide the attached patch in the hope that it is useful for all and merged to master. 
[001-Reporting.patch](https://github.com/blackducksoftware/hub-rest-api-python/files/10918968/001-Reporting.patch)

**Comment by OffBy0x01** [comment]
Closing as stale - feel free to reopen if still needed

**Comment by bmos1** [comment]
What does stale mean? We are using the patch in production to do reporting. As far as I know the python blackduck client has still the same issues, hence it is not compatible with the current REST API. Should we try to contact Synopsys support?
