### ISSUE TITLE
Add ProjectGroups.py and extend HubInstance Rest API

### ISSUE THREAD

**Issue by ChriOp** [blackducksoftware/hub-rest-api-python#240]
In order to manage project groups via the REST API I suggest to add a new class. For bigger organizations / many projects an automated sorting will make the manual step via the UI obsolete.

**Comment by OffBy0x01** [comment]
HubInstance has been deprecated in favour of the client interface and will not be receiving further updates. 

That said, it should be possible to do everything you need to do with client. The new interface is intentionally lean, as the the expansive convenience methods of HubInstance were impossible to maintain as a (mostly) community driven project. 

If you need help with something specific and have some examples of what you have tried/what you are trying to achieve we (the community) can usually help. 

If you want someone to add functionality for you, you should reach out to your technical account manager or sales engineer instead as this report isn't actively monitored.
