### ISSUE TITLE
Filter Project Names

### ISSUE THREAD

**Issue by RamkumarNagarajanMuthiah** [blackducksoftware/hub-rest-api-python#241]
I could able to set the limit to pull the project names like below,

hub = HubInstance()
projects = hub.get_projects(limit=999)

Is there any way to filter the project names starting with particular string?

projects = hub.get_projects(limit=999, project_name="App1*") ?

**Comment by OffBy0x01** [comment]
Using client you could do something like this (untested):

```
import re
from blackduck import Client

bd = Client(base_url='your.blackduck.instance', token='your token' ) 
pattern='App*' 
matching_projects = [project if re.match(pattern, project['name']) for project in bd.get_resource('projects')]
```
