### ISSUE TITLE
Get users using new client is not working

### ISSUE THREAD

**Issue by Ripurwar80** [blackducksoftware/hub-rest-api-python#243]
Hey guys, 
I'm trying to use the Blackduck client to fetch the project name and users.
```python
for user in bd.get_resource("users"):
    print(f"User: {user['userName']}, First Name: {user['firstName']}, Last Name: {user['lastName']}")
```

it's working fine with the projects but while fetching the users it’s giving an error. "KeyError: "resource name 'users' not found in available resources"

Can someone please help on this

**Comment by OffBy0x01** [comment]
Double check you have access to it, I've just tested exactly as above and it worked.

When you get that KeyError it should also show you what resources you have access to, if not you can manually query it with the following:

```python
for resource in bd.list_resource():
  print(resource)
```
