### ISSUE TITLE
In Components.py function search_component builds url incorrect

### ISSUE THREAD

**Issue by JunkerJeremias** [blackducksoftware/hub-rest-api-python#274]
In [Components.py](https://github.com/blackducksoftware/hub-rest-api-python/blob/master/blackduck/Components.py) the method search_components seems to build the url incorrectly:
```
def search_components(self, search_str_or_query, limit=100, parameters={}):
    if limit:
        parameters.update({'limit':limit})
    if search_str_or_query.startswith("q="):
        # allow caller to override original behavior with their own query
        query = search_str_or_query
    else:
        # maintain original, somewhat flawed behavior
        query = "q=name:{}".format(search_str_or_query)
    parm_str = self._get_parameter_string(parameters)
    url = self.get_apibase() + "/search/components{}&{}".format(parm_str, query)
    response = self.execute_get(url)
    return response.json()
```
 Here `url = self.get_apibase() + "/search/components{}&{}".format(parm_str, query)` "search" is added to the url which seems to be wrong. At least when I remove that part I get the expected response instead of an error `core.default.404.not_found_with_uri`.

Our server runs version 2024.4.1.

**Comment by OffBy0x01** [comment]
That's part of the old unsupported HubClient interface. There's no guarantee it'll continue to work in new releases of hub as it relies on internal APIS that change frequently.

Only the Client interface is guaranteed - it relies entirely on public APIs.
