### ISSUE TITLE
get all project names

### ISSUE THREAD

**Issue by continuum-aditya-pingale** [blackducksoftware/hub-rest-api-python#66]
I need to get all project names in my blackduck
Tried 
projects = hub.get_projects()
further massaging json data to get names.
but i get only 100 names instead of 300 + projects which I have

**Comment by gsnyder2007** [comment]
Did you set the limit parameter? Limit probably defaults to 100.

Glenn Snyder
Synopsys Black Duck SA
________________________________

**Comment by continuum-aditya-pingale** [comment]
thank you. That works
