### ISSUE TITLE
No code_locations.json in test/data

### ISSUE THREAD

**Issue by JoaoDDuarte** [blackducksoftware/hub-rest-api-python#90]
When building this package from source, pytest fails as there is no `code_locations.json` in the directory `test/data`. This can be clearly seen in by browsing to the `test/data` folder on Github. Hence, on line 477 in the file `test_hub_rest_api_python.py`

`data = json.load((shared_datadir / 'code_locations.json').open())
`

will always fail. I had to create my own using some json provided by a user in the issues page, which successfully passes all the pytest tests.

**Comment by pjsnps** [comment]
`[pjalajas@sup-pjalajas-hub test]$ date ; date --utc ; hostname ; pytest                                                                                                                                                  
Wed Oct 28 20:18:38 EDT 2020
Thu Oct 29 00:18:38 UTC 2020
sup-pjalajas-hub.dc1.lan
================================================================================================== test session starts ==================================================================================================
platform linux -- Python 3.6.8, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/pjalajas/Documents/dev/hub/api/hub-rest-api-python
plugins: requests-mock-1.8.0, datadir-1.3.1
collected 42 items                                                                                                                                                                                                      

test_hub_rest_api_python.py ........................................EE                                                                                                                                            [100%]

======================================================================================================== ERRORS =========================================================================================================
_____________________________________________________________________________________ ERROR at setup of test_get_codelocations_all ______________________________________________________________________________________

requests_mock = <requests_mock.mocker.Mocker object at 0x7fe30c1d0ef0>, shared_datadir = PosixPath('/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_all0/data')

    @pytest.fixture()
    def code_locations(requests_mock, shared_datadir):
>       data = json.load((shared_datadir / 'code_locations.json').open())

test_hub_rest_api_python.py:477: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib64/python3.6/pathlib.py:1183: in open
    opener=self._opener)
/usr/lib64/python3.6/pathlib.py:1037: in _opener
    return self._accessor.open(self, flags, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pathobj = PosixPath('/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_all0/data/code_locations.json'), args = (524288, 438)

    @functools.wraps(strfunc)
    def wrapped(pathobj, *args):
>       return strfunc(str(pathobj), *args)
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_all0/data/code_locations.json'

/usr/lib64/python3.6/pathlib.py:387: FileNotFoundError
___________________________________________________________________________________ ERROR at setup of test_get_codelocations_unmapped ___________________________________________________________________________________

requests_mock = <requests_mock.mocker.Mocker object at 0x7fe30c2420f0>, shared_datadir = PosixPath('/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_unmappe0/data')

    @pytest.fixture()
    def code_locations(requests_mock, shared_datadir):
>       data = json.load((shared_datadir / 'code_locations.json').open())

test_hub_rest_api_python.py:477: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib64/python3.6/pathlib.py:1183: in open
    opener=self._opener)
/usr/lib64/python3.6/pathlib.py:1037: in _opener
    return self._accessor.open(self, flags, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pathobj = PosixPath('/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_unmappe0/data/code_locations.json'), args = (524288, 438)

    @functools.wraps(strfunc)
    def wrapped(pathobj, *args):
>       return strfunc(str(pathobj), *args)
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_unmappe0/data/code_locations.json'

/usr/lib64/python3.6/pathlib.py:387: FileNotFoundError
================================================================================================ short test summary info ================================================================================================
ERROR test_hub_rest_api_python.py::test_get_codelocations_all - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_all0/data/code_locations.json'
ERROR test_hub_rest_api_python.py::test_get_codelocations_unmapped - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-pjalajas/pytest-1/test_get_codelocations_unmappe0/data/code_locations.json'
============================================================================================= 40 passed, 2 errors in 0.74s ==============================================================================================`
